In [2]:
import torch

In [30]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = torch.nn.Linear(3,4)
    def forward(self, x):
        return self.l1(x)

netw = Net()

In [31]:
netw.state_dict()

OrderedDict([('l1.weight',
              tensor([[ 0.1991,  0.2266, -0.2486],
                      [ 0.1168, -0.2772,  0.3883],
                      [ 0.1935, -0.1213, -0.0644],
                      [-0.3542, -0.3015,  0.1537]])),
             ('l1.bias', tensor([-0.1988, -0.0141, -0.1995, -0.2622]))])

In [32]:
torch.save(netw.state_dict(), "saved_model_state_dict.pth")
torch.save(netw, "saved_model_obj.pth")

In [33]:
loaded_state_dict = torch.load("saved_model_state_dict.pth")
loaded_model_obj = torch.load("saved_model_obj.pth")
loaded_state_dict, loaded_model_obj

(OrderedDict([('l1.weight',
               tensor([[ 0.1991,  0.2266, -0.2486],
                       [ 0.1168, -0.2772,  0.3883],
                       [ 0.1935, -0.1213, -0.0644],
                       [-0.3542, -0.3015,  0.1537]])),
              ('l1.bias', tensor([-0.1988, -0.0141, -0.1995, -0.2622]))]),
 Net(
   (l1): Linear(in_features=3, out_features=4, bias=True)
 ))

In [34]:
model_from_state_dict = Net()
model_from_state_dict.state_dict()

OrderedDict([('l1.weight',
              tensor([[ 0.2313,  0.4947, -0.0262],
                      [ 0.4036,  0.0686, -0.3522],
                      [-0.3836, -0.3913,  0.4994],
                      [-0.4201,  0.4015, -0.2233]])),
             ('l1.bias', tensor([-0.0244, -0.1988,  0.3134,  0.2689]))])

In [35]:
model_from_state_dict.load_state_dict(loaded_state_dict)

<All keys matched successfully>

In [36]:
model_from_state_dict.state_dict()

OrderedDict([('l1.weight',
              tensor([[ 0.1991,  0.2266, -0.2486],
                      [ 0.1168, -0.2772,  0.3883],
                      [ 0.1935, -0.1213, -0.0644],
                      [-0.3542, -0.3015,  0.1537]])),
             ('l1.bias', tensor([-0.1988, -0.0141, -0.1995, -0.2622]))])