In [6]:
import torch
from time import time
from torch import nn, optim
from torchvision import datasets, transforms

In [4]:
DOWNLOAD = False
train_path = r"C:\Users\hbse\projects\data\metrics\train"
test_path = r"C:\Users\hbse\projects\data\metrics\test"

In [7]:
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,))])

In [8]:
trainset = datasets.MNIST(train_path, download=DOWNLOAD, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)#, pin_memory=True, pin_memory_device="cuda")

In [9]:
for i, (imgs, labels) in enumerate(trainloader):
    print(i, imgs.shape, imgs.device, imgs.get_device())

0 torch.Size([64, 1, 28, 28]) cpu -1
1 torch.Size([64, 1, 28, 28]) cpu -1
2 torch.Size([64, 1, 28, 28]) cpu -1
3 torch.Size([64, 1, 28, 28]) cpu -1
4 torch.Size([64, 1, 28, 28]) cpu -1
5 torch.Size([64, 1, 28, 28]) cpu -1
6 torch.Size([64, 1, 28, 28]) cpu -1
7 torch.Size([64, 1, 28, 28]) cpu -1
8 torch.Size([64, 1, 28, 28]) cpu -1
9 torch.Size([64, 1, 28, 28]) cpu -1
10 torch.Size([64, 1, 28, 28]) cpu -1
11 torch.Size([64, 1, 28, 28]) cpu -1
12 torch.Size([64, 1, 28, 28]) cpu -1
13 torch.Size([64, 1, 28, 28]) cpu -1
14 torch.Size([64, 1, 28, 28]) cpu -1
15 torch.Size([64, 1, 28, 28]) cpu -1
16 torch.Size([64, 1, 28, 28]) cpu -1
17 torch.Size([64, 1, 28, 28]) cpu -1
18 torch.Size([64, 1, 28, 28]) cpu -1
19 torch.Size([64, 1, 28, 28]) cpu -1
20 torch.Size([64, 1, 28, 28]) cpu -1
21 torch.Size([64, 1, 28, 28]) cpu -1
22 torch.Size([64, 1, 28, 28]) cpu -1
23 torch.Size([64, 1, 28, 28]) cpu -1
24 torch.Size([64, 1, 28, 28]) cpu -1
25 torch.Size([64, 1, 28, 28]) cpu -1
26 torch.Size([64, 1, 

In [10]:
imgs.to('cuda')

tensor([[[[-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          ...,
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.]]],


        [[[-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          ...,
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.]]],


        [[[-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          ...,
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., -1., -1.,  ..., -1., -1., -1.]]],


        ...,


        [[[-1., -1., -1.,  ..., -1., -1., -1.],
          [-1., 

In [11]:
imgs.device

device(type='cpu')

In [12]:
imgs = imgs.to('cuda')
imgs.device

device(type='cuda', index=0)

## create neural net

In [19]:
input_size = 784
hidden_sizes = [128, 64]
output_size = 10

model = nn.Sequential(nn.Linear(input_size, hidden_sizes[0]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[0], hidden_sizes[1]),
                      nn.ReLU(),
                      nn.Linear(hidden_sizes[1], output_size),
                      nn.LogSoftmax(dim=1))
print(model)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): LogSoftmax(dim=1)
)


In [20]:
list(model.children())

[Linear(in_features=784, out_features=128, bias=True),
 ReLU(),
 Linear(in_features=128, out_features=64, bias=True),
 ReLU(),
 Linear(in_features=64, out_features=10, bias=True),
 LogSoftmax(dim=1)]

In [21]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0004, -0.0350,  0.0340,  ...,  0.0175, -0.0002, -0.0142],
         [ 0.0141, -0.0117,  0.0254,  ..., -0.0093,  0.0172, -0.0240],
         [-0.0028,  0.0027, -0.0028,  ...,  0.0114,  0.0203, -0.0159],
         ...,
         [-0.0012, -0.0173,  0.0264,  ..., -0.0088, -0.0213,  0.0292],
         [ 0.0025, -0.0168,  0.0015,  ...,  0.0103,  0.0322, -0.0020],
         [-0.0003,  0.0161, -0.0213,  ..., -0.0242, -0.0352, -0.0326]],
        requires_grad=True),
 Parameter containing:
 tensor([-2.3115e-02, -1.0818e-02, -2.2250e-03, -2.7058e-02,  1.8237e-02,
          3.8807e-03,  3.5038e-02, -2.2031e-02, -2.9286e-02,  3.4954e-02,
          3.8008e-04, -1.3354e-02, -3.4601e-02,  3.0470e-02,  2.2164e-02,
          3.0041e-02, -4.0823e-03, -2.4165e-02,  1.6721e-02,  3.5488e-03,
          1.4637e-02,  3.4527e-02,  4.7804e-03,  1.6789e-02,  2.7129e-02,
          2.0367e-02, -5.3942e-03,  1.7201e-02, -1.3085e-02,  5.4103e-03,
          4.0466e-04, -1.7948e-02, -2.90

In [22]:
list(model.parameters())[0].device

device(type='cpu')

In [23]:
model.cuda()

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): LogSoftmax(dim=1)
)

In [24]:
list(model.parameters())[0].device

device(type='cuda', index=0)

In [16]:
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003, momentum=0.9)
time0 = time()
epochs = 3
print(f"Device used: {list(model.parameters())[0].device}")
print(f"Start training...  Time (in minutes) ={(time()-time0)/60:.2f}")
for e in range(epochs):
    running_loss = 0
    for images, labels in trainloader:
        images, labels = images.cuda(), labels.cuda()
        # print(images.device, list(model.parameters())[0].device)
        # Flatten MNIST images into a 784 long vector
        images = images.view(images.shape[0], -1)
    
        # Training pass
        optimizer.zero_grad()
        
        output = model(images)
        loss = criterion(output, labels)
        
        #This is where the model learns by backpropagating
        loss.backward()
        
        #And optimizes its weights here
        optimizer.step()
        
        running_loss += loss.item()
    else:
        print("Epoch {} - Training loss: {:.6f}".format(e, running_loss/len(trainloader)), end="")
        print(f"  Time (in minutes)={(time()-time0)/60:.2f}")
print(f"\nTotal Training Time (in minutes)={(time()-time0)/60:.2f}")

Device used: cuda:0
Start training...  Time (in minutes) =0.00
Epoch 0 - Training loss: 0.630556  Time (in minutes)=0.15
Epoch 1 - Training loss: 0.286405  Time (in minutes)=0.30
Epoch 2 - Training loss: 0.224529  Time (in minutes)=0.44

Total Training Time (in minutes)=0.44


### now compare with time to run if variables are allocated in the CPU

In [17]:
model.cpu()

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=64, bias=True)
  (3): ReLU()
  (4): Linear(in_features=64, out_features=10, bias=True)
  (5): LogSoftmax(dim=1)
)

In [18]:
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003, momentum=0.9)
time0 = time()
epochs = 3
print(f"Device used: {list(model.parameters())[0].device}")
print(f"Start training...  Time (in minutes) ={(time()-time0)/60:.2f}")
for e in range(epochs):
    running_loss = 0
    for images, labels in trainloader:
        images, labels = images.cpu(), labels.cpu()
        # print(images.device, list(model.parameters())[0].device)
        # Flatten MNIST images into a 784 long vector
        images = images.view(images.shape[0], -1)
    
        # Training pass
        optimizer.zero_grad()
        
        output = model(images)
        loss = criterion(output, labels)
        
        #This is where the model learns by backpropagating
        loss.backward()
        
        #And optimizes its weights here
        optimizer.step()
        
        running_loss += loss.item()
    else:
        print("Epoch {} - Training loss: {:.6f}".format(e, running_loss/len(trainloader)), end="")
        print(f"  Time (in minutes)={(time()-time0)/60:.2f}")
print(f"\nTotal Training Time (in minutes)={(time()-time0)/60:.2f}")

Device used: cpu
Start training...  Time (in minutes) =0.00
Epoch 0 - Training loss: 0.179789  Time (in minutes)=0.30
Epoch 1 - Training loss: 0.150125  Time (in minutes)=0.62
Epoch 2 - Training loss: 0.127731  Time (in minutes)=0.94

Total Training Time (in minutes)=0.94
